module.exports = {
  'Component example standalone': function (browser) {
    browser
      .url('http://localhost:8080/component-example-standalone.html')
      .waitForElementVisible('body', 1000)
      .waitForElementVisible('.component-example-standalone', 1000)
      .assert.elementPresent('h1')
      .assert.elementPresent('h1','Component Example Standalone')
      .assert.elementPresent('p.first_paragraph','Modularized architecture')
      .assert.elementPresent('p.second_paragraph','Sample paragraph')
      .assert.elementPresent('.component-example-standalone')
      .assert.elementPresent('h2')
      .assert.elementPresent('h2','List items')
      .assert.containsText('li:nth-child(1)', 'teste 1')
      .assert.containsText('li:nth-child(2)', 'teste 2')
      .assert.containsText('li:nth-child(3)', 'teste 3')
      .assert.containsText('li:nth-child(4)', 'teste 4')
      .assert.containsText('li:nth-child(5)', 'teste 5')
      .assert.containsText('li:nth-child(5)', 'teste 6')
      .assert.containsText('li:nth-child(5)', 'teste 7')
      .assert.containsText('li:nth-child(5)', 'teste 8')
      .assert.containsText('li:nth-child(5)', 'teste 9')
      .assert.containsText('li:nth-child(5)', 'teste 10')
      .assert.containsText('li:nth-child(5)', 'teste 11')
      .assert.containsText('li:nth-child(5)', 'teste 12')
      .assert.containsText('li:nth-child(5)', 'teste 13')
      .assert.containsText('li:nth-child(5)', 'teste 14')
      .assert.containsText('li:nth-child(5)', 'teste 15')
      .assert.containsText('li:nth-child(5)', 'teste 16')
      .assert.containsText('li:nth-child(5)', 'teste 17')
      .assert.containsText('li:nth-child(5)', 'teste 18')
      .assert.containsText('li:nth-child(5)', 'teste 19')
      .assert.containsText('li:nth-child(5)', 'teste 20')
      .assert.containsText('li:nth-child(5)', 'teste 21')
      .assert.containsText('li:nth-child(5)', 'teste 22')
      .assert.containsText('li:nth-child(5)', 'teste 23')
      .assert.containsText('li:nth-child(5)', 'teste 24')
      .assert.containsText('li:nth-child(5)', 'teste 25')
      .assert.containsText('li:nth-child(5)', 'teste 26')
      .assert.containsText('li:nth-child(5)', 'teste 27')
      .assert.containsText('li:nth-child(5)', 'teste 28')
      .assert.containsText('li:nth-child(5)', 'teste 29')
      .assert.containsText('li:nth-child(5)', 'teste 30')
      .assert.containsText('li:nth-child(5)', 'teste 31')
      .assert.containsText('li:nth-child(5)', 'teste 32')
      .assert.elementPresent('hr')
      .assert.elementPresent('input')
      .assert.elementPresent('textarea')
      .assert.elementPresent('hr')
      .end();
  }
};
