module.exports = {
  'Component example standalone': function (browser) {
    browser
      .url('http://localhost:8080/component-example-standalone.html')
      .waitForElementVisible('body', 1000)
      .waitForElementVisible('.component-example-standalone', 1000)
      .assert.elementPresent('h1')
      .assert.elementPresent('h1','Component Example Standalone')
      .assert.elementPresent('p.first_paragraph','Modularized architecture')
      .assert.elementPresent('p.second_paragraph','Sample paragraph')
      .assert.elementPresent('.component-example-standalone')
      .assert.elementPresent('h2')
      .assert.elementPresent('h2','List items')
      .assert.containsText('li:nth-child(1)', 'teste 1')
      .assert.containsText('li:nth-child(2)', 'teste 2')
      .assert.containsText('li:nth-child(3)', 'teste 3')
      .assert.containsText('li:nth-child(4)', 'teste 4')
      .assert.containsText('li:nth-child(5)', 'teste 5')
      .assert.containsText('li:nth-child(6)', 'teste 6')
      .assert.containsText('li:nth-child(7)', 'teste 7')
      .assert.containsText('li:nth-child(8)', 'teste 8')
      .assert.containsText('li:nth-child(9)', 'teste 9')
      .assert.containsText('li:nth-child(10)', 'teste 10')
      .assert.containsText('li:nth-child(11)', 'teste 11')
      .assert.containsText('li:nth-child(12)', 'teste 12')
      .assert.containsText('li:nth-child(13)', 'teste 13')
      .assert.containsText('li:nth-child(14)', 'teste 14')
      .assert.containsText('li:nth-child(15)', 'teste 15')
      .assert.containsText('li:nth-child(16)', 'teste 16')
      .assert.containsText('li:nth-child(17)', 'teste 17')
      .assert.containsText('li:nth-child(18)', 'teste 18')
      .assert.containsText('li:nth-child(19)', 'teste 19')
      .assert.containsText('li:nth-child(20)', 'teste 20')
      .assert.containsText('li:nth-child(21)', 'teste 21')
      .assert.containsText('li:nth-child(22)', 'teste 22')
      .assert.containsText('li:nth-child(23)', 'teste 23')
      .assert.containsText('li:nth-child(24)', 'teste 24')
      .assert.containsText('li:nth-child(25)', 'teste 25')
      .assert.containsText('li:nth-child(26)', 'teste 26')
      .assert.containsText('li:nth-child(27)', 'teste 27')
      .assert.containsText('li:nth-child(28)', 'teste 28')
      .assert.containsText('li:nth-child(29)', 'teste 29')
      .assert.containsText('li:nth-child(30)', 'teste 30')
      .assert.containsText('li:nth-child(31)', 'teste 31')
      .assert.containsText('li:nth-child(32)', 'teste 32')
      .assert.containsText('li:nth-child(33)', 'teste 33')
      .assert.containsText('li:nth-child(34)', 'teste 34')
      .assert.containsText('li:nth-child(35)', 'teste 35')
      .assert.containsText('li:nth-child(36)', 'teste 36')
      .assert.containsText('li:nth-child(37)', 'teste 37')
      .assert.containsText('li:nth-child(38)', 'teste 38')
      .assert.containsText('li:nth-child(39)', 'teste 39')
      .assert.containsText('li:nth-child(40)', 'teste 40')
      .assert.containsText('li:nth-child(41)', 'teste 41')
      .assert.containsText('li:nth-child(42)', 'teste 42')
      .assert.containsText('li:nth-child(43)', 'teste 43')
      .assert.containsText('li:nth-child(44)', 'teste 44')
      .assert.containsText('li:nth-child(45)', 'teste 45')
      .assert.containsText('li:nth-child(46)', 'teste 46')
      .assert.containsText('li:nth-child(47)', 'teste 47')
      .assert.containsText('li:nth-child(48)', 'teste 48')
      .assert.containsText('li:nth-child(49)', 'teste 49')
      .assert.containsText('li:nth-child(50)', 'teste 50')
      .assert.containsText('li:nth-child(51)', 'teste 51')
      .assert.containsText('li:nth-child(52)', 'teste 52')
      .assert.containsText('li:nth-child(53)', 'teste 53')
      .assert.containsText('li:nth-child(54)', 'teste 54')
      .assert.containsText('li:nth-child(55)', 'teste 55')
      .assert.containsText('li:nth-child(56)', 'teste 56')
      .assert.containsText('li:nth-child(57)', 'teste 57')
      .assert.containsText('li:nth-child(58)', 'teste 58')
      .assert.containsText('li:nth-child(59)', 'teste 59')
      .assert.containsText('li:nth-child(60)', 'teste 60')
      .assert.containsText('li:nth-child(61)', 'teste 61')
      .assert.containsText('li:nth-child(62)', 'teste 62')
      .assert.containsText('li:nth-child(63)', 'teste 63')
      .assert.containsText('li:nth-child(64)', 'teste 64')
      .assert.containsText('li:nth-child(65)', 'teste 65')
      .assert.containsText('li:nth-child(66)', 'teste 66')
      .assert.containsText('li:nth-child(67)', 'teste 67')
      .assert.containsText('li:nth-child(68)', 'teste 68')
      .assert.containsText('li:nth-child(69)', 'teste 69')
      .assert.containsText('li:nth-child(70)', 'teste 70')
      .assert.containsText('li:nth-child(71)', 'teste 71')
      .assert.containsText('li:nth-child(72)', 'teste 72')
      .assert.containsText('li:nth-child(73)', 'teste 73')
      .assert.containsText('li:nth-child(74)', 'teste 74')
      .assert.containsText('li:nth-child(75)', 'teste 75')
      .assert.containsText('li:nth-child(76)', 'teste 76')
      .assert.containsText('li:nth-child(77)', 'teste 77')
      .assert.containsText('li:nth-child(78)', 'teste 78')
      .assert.containsText('li:nth-child(79)', 'teste 79')
      .assert.containsText('li:nth-child(80)', 'teste 80')
      .assert.containsText('li:nth-child(81)', 'teste 81')
      .assert.containsText('li:nth-child(82)', 'teste 82')
      .assert.containsText('li:nth-child(83)', 'teste 83')
      .assert.containsText('li:nth-child(84)', 'teste 84')
      .assert.containsText('li:nth-child(85)', 'teste 85')
      .assert.containsText('li:nth-child(86)', 'teste 86')
      .assert.containsText('li:nth-child(87)', 'teste 87')
      .assert.containsText('li:nth-child(88)', 'teste 88')
      .assert.containsText('li:nth-child(89)', 'teste 89')
      .assert.containsText('li:nth-child(90)', 'teste 90')
      .assert.containsText('li:nth-child(91)', 'teste 91')
      .assert.containsText('li:nth-child(92)', 'teste 92')
      .assert.containsText('li:nth-child(93)', 'teste 93')
      .assert.containsText('li:nth-child(94)', 'teste 94')
      .assert.containsText('li:nth-child(95)', 'teste 95')
      .assert.containsText('li:nth-child(96)', 'teste 96')
      .assert.containsText('li:nth-child(97)', 'teste 97')
      .assert.containsText('li:nth-child(98)', 'teste 98')
      .assert.containsText('li:nth-child(99)', 'teste 99')
      .assert.containsText('li:nth-child(100)', 'teste 100')
      .assert.elementPresent('hr')
      .assert.elementPresent('input')
      .assert.elementPresent('textarea')
      .assert.elementPresent('hr')
      .end();
  }
};
