module.exports = {
  'Component example standalone': function (browser) {
    browser
      .url('http://localhost:8080/component-example-standalone.html')
      .waitForElementVisible('body', 1000)
      .waitForElementVisible('.component-example-standalone', 1000)
      .assert.elementPresent('h1')
      .assert.elementPresent('h1','Component Example Standalone')
      .assert.elementPresent('p.first_paragraph','Modularized architecture')
      .assert.elementPresent('p.second_paragraph','Sample paragraph')
      .assert.elementPresent('.component-example-standalone')
      .assert.elementPresent('h2')
      .assert.elementPresent('h2','List items')
      .assert.containsText('li:nth-child(1)', 'teste 1')
      .assert.containsText('li:nth-child(2)', 'teste 2')
      .assert.containsText('li:nth-child(3)', 'teste 3')
      .assert.containsText('li:nth-child(4)', 'teste 4')
      .assert.containsText('li:nth-child(5)', 'teste 5')
      .assert.containsText('li:nth-child(6)', 'teste 6')
      .assert.containsText('li:nth-child(7)', 'teste 7')
      .assert.containsText('li:nth-child(8)', 'teste 8')
      .assert.containsText('li:nth-child(9)', 'teste 9')
      .assert.containsText('li:nth-child(10)', 'teste 10')
      .assert.containsText('li:nth-child(11)', 'teste 11')
      .assert.containsText('li:nth-child(12)', 'teste 12')
      .assert.containsText('li:nth-child(13)', 'teste 13')
      .assert.containsText('li:nth-child(14)', 'teste 14')
      .assert.containsText('li:nth-child(15)', 'teste 15')
      .assert.containsText('li:nth-child(16)', 'teste 16')
      .assert.containsText('li:nth-child(17)', 'teste 17')
      .assert.containsText('li:nth-child(18)', 'teste 18')
      .assert.containsText('li:nth-child(19)', 'teste 19')
      .assert.containsText('li:nth-child(20)', 'teste 20')
      .assert.containsText('li:nth-child(21)', 'teste 21')
      .assert.containsText('li:nth-child(22)', 'teste 22')
      .assert.containsText('li:nth-child(23)', 'teste 23')
      .assert.containsText('li:nth-child(24)', 'teste 24')
      .assert.containsText('li:nth-child(25)', 'teste 25')
      .assert.containsText('li:nth-child(26)', 'teste 26')
      .assert.containsText('li:nth-child(27)', 'teste 27')
      .assert.containsText('li:nth-child(28)', 'teste 28')
      .assert.containsText('li:nth-child(29)', 'teste 29')
      .assert.containsText('li:nth-child(30)', 'teste 30')
      .assert.containsText('li:nth-child(31)', 'teste 31')
      .assert.containsText('li:nth-child(32)', 'teste 32')
      .assert.elementPresent('hr')
      .assert.elementPresent('input')
      .assert.elementPresent('textarea')
      .assert.elementPresent('hr')
      .end();
  }
};
